# Generated by Django 4.0.5 on 2022-06-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockAlgebraEge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_algebra_ege', models.CharField(max_length=255)),
                ('file_algebra_ege', models.FileField(upload_to='algebra/')),
            ],
            options={
                'verbose_name': 'Программа блока Алгебра',
                'verbose_name_plural': 'Программы блоков Алгебра',
            },
        ),
        migrations.CreateModel(
            name='BlockGeometriaEge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_geometria_ege', models.CharField(max_length=255)),
                ('file_geometria_ege', models.FileField(upload_to='geometria/')),
            ],
            options={
                'verbose_name': 'Программа блока Геометрия',
                'verbose_name_plural': 'Программы блоков Геометрия',
            },
        ),
        migrations.CreateModel(
            name='VariantEge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ege', models.CharField(max_length=255)),
                ('file_ege', models.FileField(upload_to='ege/')),
            ],
            options={
                'verbose_name': 'Вариант ЕГЭ',
                'verbose_name_plural': 'Варианты ЕГЭ',
            },
        ),
    ]
