# Generated by Django 4.0.5 on 2022-06-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockAlgebraEge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_algebra_ege', models.CharField(max_length=255, verbose_name='Название блока')),
                ('file_algebra_ege', models.FileField(upload_to='algebra/', verbose_name='Файл блока')),
            ],
            options={
                'verbose_name': 'Программа блока Алгебра ЕГЭ',
                'verbose_name_plural': 'Программы блоков Алгебра ЕГЭ',
            },
        ),
        migrations.CreateModel(
            name='BlockGeometriaEge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_geometria_ege', models.CharField(max_length=255, verbose_name='Название блока')),
                ('file_geometria_ege', models.FileField(upload_to='geometria/', verbose_name='Файл блока')),
            ],
            options={
                'verbose_name': 'Программа блока Геометрия ЕГЭ',
                'verbose_name_plural': 'Программы блоков Геометрия ЕГЭ',
            },
        ),
        migrations.CreateModel(
            name='VariantEge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ege', models.CharField(max_length=255, verbose_name='Номер варианта')),
                ('file_ege', models.FileField(upload_to='ege/', verbose_name='Файл варианта')),
            ],
            options={
                'verbose_name': 'Вариант ЕГЭ',
                'verbose_name_plural': 'Варианты ЕГЭ',
            },
        ),
    ]
