# Generated by Django 4.0.5 on 2022-06-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetodicalOneCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('file', models.FileField(upload_to='metodical/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Методические указания 1 курса',
                'verbose_name_plural': 'Методические указания 1 курса',
            },
        ),
        migrations.CreateModel(
            name='MetodicalTwoCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('file', models.FileField(upload_to='metodical/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Методические указания 2 курса',
                'verbose_name_plural': 'Методические указания 2 курса',
            },
        ),
        migrations.CreateModel(
            name='OneCourseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тема')),
                ('body', models.TextField(verbose_name='Краткая информация')),
                ('video', models.FileField(upload_to='ocv/', verbose_name='Видеофайл')),
            ],
            options={
                'verbose_name': 'Видеоуроки 1 курс',
                'verbose_name_plural': 'Видеоуроки 1 курс',
            },
        ),
        migrations.CreateModel(
            name='TwoCourseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тема')),
                ('body', models.TextField(verbose_name='Краткая информация')),
                ('video', models.FileField(upload_to='otv/', verbose_name='Видеофайл')),
            ],
            options={
                'verbose_name': 'Видеоуроки 2 курс',
                'verbose_name_plural': 'Видеоуроки 2 курс',
            },
        ),
    ]
