# Generated by Django 4.0.5 on 2022-06-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('group', models.CharField(max_length=6, verbose_name='Группа')),
                ('email', models.EmailField(max_length=200, verbose_name='Почта')),
                ('message', models.TextField(max_length=1000, verbose_name='Обращение')),
            ],
            options={
                'verbose_name': 'Обратную связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
    ]
